# help link 1: https://blog.logrocket.com/flutter-ci-cd-using-github-actions/
# help link 2: https://github.com/marketplace/actions/flutter-action
# android CD: https://gist.github.com/vinicioslc/b9bd073c8013a726033a999db68a45be

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
      
      
jobs:
  scanning:
      name: GitGuardian scan
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0 # fetch all history so multiple commits can be scanned
        - name: GitGuardian scan
          uses: GitGuardian/ggshield-action@master
          env:
            GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
            GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
            GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
            GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
            GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  sonarqube:
    needs: scanning
    name: Quality Gate
    runs-on: ubuntu-latest  
    steps:
    # - uses: actions/checkout@master
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter --version
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.projectKey=sspf 
           -Dsonar.sources=./lib 
           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
